import { mkdir, rm, writeFile, copyFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { careers, companies, coreValues, industries, navItems, pageMeta, projects, services, site, timeline, values } from '../src/data.js';

const root = dirname(fileURLToPath(import.meta.url)).replace('/scripts', '');
const out = join(root, 'dist');
const siteOut = root;
const esc = (s) => String(s).replace(/[&<>"']/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[m]));
const slug = (s) => s.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const pathOf = (route) => route === '/' ? join(out, 'index.html') : join(out, route, 'index.html');
const routePrefix = (route) => route === '/' ? '' : '../';
function relativize(html, route) {
  const prefix = routePrefix(route);
  return html
    .replace(/(href|src)="\/(?!\/|#)/g, `$1="${prefix}`)
    .replace(/href=""/g, 'href="./"');
}

function button(label, href, variant = 'primary') { return `<a class="btn btn--${variant}" href="${href}">${label}</a>`; }
function sectionHeading(kicker, title, text = '') { return `<div class="section-heading"><span class="eyebrow">${kicker}</span><h2>${title}</h2>${text ? `<p>${text}</p>` : ''}</div>`; }
function chips(items) { return `<div class="chips">${items.map((x) => `<span class="chip">${x}</span>`).join('')}</div>`; }
function imageBlock(label) { return `<div class="image-shell" role="img" aria-label="Placeholder for ${esc(label)} project or facility image"><span>${esc(label)}</span></div>`; }
function responsiveImage(src, alt, className = '') { return `<img class="${className}" src="${src}" alt="${esc(alt)}" loading="lazy" onerror="this.dataset.failed='true';this.setAttribute('aria-hidden','true')">`; }
function statCard(value, label = '') { return `<article class="stat-card"><strong>${value}</strong>${label ? `<span>${label}</span>` : ''}</article>`; }
function companyCard(c) { return `<article class="company-card"><span class="card-number">0${companies.indexOf(c)+1}</span><h3>${c.name}</h3><p>${c.summary}</p>${chips(c.card.split(', '))}<a href="/companies/#${c.slug}" class="text-link">Explore ${c.name}</a></article>`; }
function serviceCard(s) { return `<article class="service-card"><div class="icon" aria-hidden="true">⌁</div><h3>${s[0]}</h3><p>${s[1]}</p>${chips(s[2])}</article>`; }
function industryCard(i) { return `<article class="industry-card"><h3>${i[0]}</h3><p>${i[1]}</p><dl><dt>Facility concerns</dt><dd>${i[2].join(' • ')}</dd></dl></article>`; }
function projectCard(p) { return `<article class="project-card" data-industry="${p.category}" data-company="${p.company}" data-tags="${p.tags.join('|')}">${imageBlock(p.title)}<div class="project-card__body"><span class="eyebrow">${p.category} / ${p.company}</span><h3>${p.title}</h3><p>${p.description}</p>${chips(p.tags)}</div></article>`; }
function projectPortfolioCard(p, index) { return `<button class="portfolio-card" type="button" data-project-index="${index}" data-industry="${p.category}" data-company="${p.company}" data-tags="${p.tags.join('|')}" aria-label="Open project details for ${esc(p.title)}"><span class="portfolio-card__media">${responsiveImage(p.featuredImage, p.title, 'portfolio-card__image')}<span class="portfolio-card__placeholder" aria-hidden="true">${p.icon}</span></span><span class="portfolio-card__overlay"><span class="portfolio-card__category"><span>${p.icon}</span>${p.category}</span><span class="portfolio-card__title">${p.title}</span><span class="portfolio-card__arrow" aria-hidden="true">↗</span></span></button>`; }
function projectGallerySlides(p) { return p.gallery.map((image, index) => `<figure class="project-gallery__slide" data-slide="${index}">${responsiveImage(image.src, image.alt, 'project-gallery__image')}<figcaption>${image.caption}</figcaption></figure>`).join(''); }
function expandedProjectModal() { return `<div class="project-modal" id="project-modal" aria-hidden="true"><div class="project-modal__backdrop" data-modal-close></div><section class="project-modal__panel" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="project-modal__close" type="button" data-modal-close aria-label="Close project details">×</button><div class="project-modal__info"><span class="project-modal__category" data-modal-category></span><h2 id="modal-title" data-modal-title></h2><p data-modal-description></p><dl><div><dt>Company / Division</dt><dd data-modal-company></dd></div></dl><div class="project-modal__tags" data-modal-tags></div><div class="project-modal__project-controls"><button type="button" class="gallery-arrow" data-project-prev aria-label="Previous project">← Prev</button><button type="button" class="gallery-arrow" data-project-next aria-label="Next project">Next →</button></div></div><div class="project-gallery"><div class="project-gallery__viewport" data-gallery-viewport></div><button type="button" class="gallery-arrow gallery-arrow--left" data-gallery-prev aria-label="Previous image">‹</button><button type="button" class="gallery-arrow gallery-arrow--right" data-gallery-next aria-label="Next image">›</button><div class="project-gallery__dots" data-gallery-dots></div></div></section></div>`; }
function cta(title, text, buttons) { return `<section class="cta-band"><div><span class="eyebrow">Next step</span><h2>${title}</h2><p>${text}</p></div><div class="cta-actions">${buttons}</div></section>`; }
function breadcrumbs(current) { return `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>${current}</span></nav>`; }
function hero(title, text, current = '', actions = '') { return `<section class="hero hero--page"><div class="container">${current ? breadcrumbs(current) : ''}<div class="hero__grid"><div><span class="eyebrow">SURE Group</span><h1>${title}</h1><p>${text}</p><div class="hero__actions">${actions}</div></div><div class="hero-panel">${imageBlock(title)}<div class="hero-panel__note">Commercial HVAC • Mechanical Construction • Environmental Control</div></div></div></div></section>`; }

function header(activeRoute) { return `<header class="site-header"><a class="skip-link" href="#main">Skip to content</a><div class="nav-wrap"><a class="brand" href="/" aria-label="SURE Group home"><span class="brand-mark">SG</span><span><strong>SURE Group</strong><small>Mechanical Excellence</small></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav"><span></span><span></span><span></span><span class="sr-only">Menu</span></button><nav id="primary-nav" class="primary-nav" aria-label="Primary navigation">${navItems.map(([n,h]) => `<a class="${activeRoute === h ? 'active' : ''}" href="${h}">${n}</a>`).join('')}</nav><div class="header-ctas"><a href="/contact/#quote" class="btn btn--small btn--primary">Request a Quote</a><a href="/contact/#service" class="btn btn--small btn--ghost">Schedule Service</a></div></div></header>`; }
function footer() { return `<footer class="site-footer"><div class="container footer-grid"><div><a class="brand brand--footer" href="/"><span class="brand-mark">SG</span><span><strong>SURE Group</strong><small>Mechanical Excellence</small></span></a><p>${site.description}</p><div class="badges"><span class="badge">Certified MBE</span><span class="badge">LEED AP Leadership</span><span class="badge">Safety-First Culture</span></div></div><div><h2>Companies</h2>${companies.map(c=>`<a href="/companies/#${c.slug}">${c.name}</a>`).join('')}</div><div><h2>Services</h2>${services.slice(0,6).map(s=>`<a href="/services/#${slug(s[0])}">${s[0]}</a>`).join('')}</div><div><h2>Industries</h2>${industries.slice(0,6).map(i=>`<a href="/industries/#${slug(i[0])}">${i[0]}</a>`).join('')}</div><div><h2>Contact</h2><address>${site.address.join('<br>')}<br><a href="tel:+15138981050">${site.phone}</a><br>Fax: ${site.fax}</address><div class="socials"><a href="#" aria-label="LinkedIn">in</a><a href="#" aria-label="Facebook">f</a><a href="#" aria-label="YouTube">▶</a></div></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} SURE Group. All rights reserved.</span><span>Commercial HVAC and mechanical construction for critical facilities.</span></div></footer>`; }
function layout(route, body) { const [title, desc] = pageMeta[route]; return relativize(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}</title><meta name="description" content="${desc}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Sora:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/styles.css"><script type="module" src="/assets/main.js"></script></head><body>${header(route)}<main id="main">${body}</main>${footer()}</body></html>`, route); }

function home() { return `<section class="hero"><div class="container hero__grid"><div><span class="eyebrow">Parent company of SURE Mechanical, Cincinnati Air Conditioning Company & Thermolinear</span><h1>Three trusted companies. One standard for mechanical excellence.</h1><p>SURE Group brings together SURE Mechanical, Cincinnati Air Conditioning Company, and Thermolinear to deliver HVAC construction, mechanical fabrication, service, and environmental control solutions for critical facilities across the Tri-State region.</p><div class="hero__actions">${button('Request a Quote','/contact/#quote')}${button('Explore Services','/services/','secondary')}</div></div><div class="hero-panel">${imageBlock('Cinematic mechanical construction')}<div class="hero-panel__note">Hospitals • Banks • Universities • Government • Industrial</div></div></div></section><section class="stats-strip container">${['3 Specialized Companies','85+ Years of Legacy Service','Certified Minority-Owned','24/7 Service Support','Southern Ohio, Northern Kentucky & Tri-State Region'].map(x=>statCard(x)).join('')}</section><section class="section container">${sectionHeading('Unified capacity','Built to Deliver More Under One Roof','Specialized companies aligned around engineering discipline, field craftsmanship, responsive service, and accountability.')}<div class="grid grid--3">${companies.map(companyCard).join('')}</div></section><section class="section section--light"><div class="container">${sectionHeading('Mechanical scope','Full-Service Mechanical Solutions from Design to Long-Term Support')}<div class="grid grid--4">${services.slice(0,8).map(serviceCard).join('')}</div></div></section><section class="section container">${sectionHeading('Industries','Built for Demanding Environments')}<div class="grid grid--4">${industries.map(industryCard).join('')}</div></section><section class="section section--dark"><div class="container">${sectionHeading('Project range','Project Experience That Shows the Range of Our Work')}<div class="grid grid--4">${projects.slice(0,8).map(projectCard).join('')}</div></div></section><section class="section container">${sectionHeading('Why SURE Group','Capacity, Craftsmanship, and Accountability')}<div class="grid grid--4">${values.map((v)=>`<article class="value-card"><h3>${v}</h3><p>${valueText(v)}</p></article>`).join('')}</div></section><div class="container">${cta('Built by Skilled Teams. Backed by a Safety-First Culture.','We invest in craft, apprenticeships, inclusive workforce development, and field leadership that protects people and projects.',button('Explore Careers','/careers/','secondary'))}${cta('Ready to build, upgrade, or service your mechanical systems?','Connect with the SURE Group team for project support, planned service, or custom environmental systems.',button('Request a Quote','/contact/#quote')+button('Schedule Service','/contact/#service','secondary')+button('Contact Us','/contact/','ghost'))}</div>`; }
function valueText(v){return { 'Engineering-Led Execution':'Project teams plan around constructability, performance, coordination, and lifecycle value before work reaches the field.', 'Skilled Fabrication & Installation':'Fabrication, sheet metal, piping, welding, and installation crews execute with commercial-grade precision.', 'Service Beyond the Build':'Long-term maintenance, repairs, diagnostics, and retrofit support protect critical HVAC investments.', 'Inclusive Workforce Development':'SURE Group expands opportunity while building the skilled technical workforce the region needs.'}[v];}
function about() { return `${hero('A Unified Force in Commercial HVAC','SURE Group combines the craft depth of specialty mechanical contractors with the operational discipline required for critical facilities.', 'About', button('Explore Companies','/companies/')+button('Join Our Team','/careers/','secondary'))}<section class="section container two-col"><div>${sectionHeading('Who we are','A full-service HVAC and mechanical construction group')}<p>SURE Group brings together three specialized organizations under one standard for quality, safety, responsiveness, and technical execution.</p><h3>Why SURE Group Exists</h3><p>Owners and facility leaders need a partner that can design, build, fabricate, service, maintain, and manufacture specialty environments without losing accountability between scopes.</p></div><div class="quote-card"><h2>Mission</h2><p>SURE Group delivers high-performance HVAC and mechanical solutions through experienced project teams, precision engineering, and a diverse, skilled workforce. Across every job, we prioritize quality, safety, efficiency, and long-term value for the facilities and communities we serve.</p><h2>Vision</h2><p>To be the region’s most trusted partner for HVAC and mechanical excellence by combining legacy, innovation, inclusive growth, and reliable execution.</p></div></section><section class="section section--light"><div class="container">${sectionHeading('Core values','The standard behind the work')}<div class="grid grid--6">${coreValues.map(v=>`<article class="mini-card"><h3>${v}</h3></article>`).join('')}</div></div></section><section class="section container">${sectionHeading('Company timeline','Legacy, growth, and unified capability')}<ol class="timeline">${timeline.map(t=>`<li><time>${t[0]}</time><p>${t[1]}</p></li>`).join('')}</ol></section><section class="section container two-col"><div>${sectionHeading('Leadership','Chukwuma “Chuma” Ekwueme, President')}<p>Chukwuma “Chuma” Ekwueme founded SURE Mechanical and leads SURE Group with a mechanical engineering background, a Master’s of Engineering from the University of Cincinnati, LEED AP credentials, and involvement with ASHRAE, ASME, and USGBC.</p><p>He is a lean construction enthusiast and an advocate for minority participation in technical construction fields.</p></div><div><h2>Certifications</h2><div class="badges badges--large"><span class="badge">Certified Minority-Owned</span><span class="badge">LEED AP</span><span class="badge">ASHRAE / ASME / USGBC</span><span class="badge">Safety Program Placeholder</span></div></div></section><div class="container">${cta('Bring your skill to a growing mechanical group.','Explore career paths in HVAC service, fabrication, piping, engineering, estimating, project management, and operations.',button('Explore Careers','/careers/'))}</div>`; }
function companiesPage(){return `${hero('Three Companies. One Trusted Standard.','Each SURE Group company brings focused capabilities while sharing one commitment to quality, safety, and accountable delivery.', 'Companies', button('Request a Quote','/contact/#quote'))}<section class="section container company-sections">${companies.map(c=>`<article id="${c.slug}" class="company-section"><div>${imageBlock(c.name)}</div><div><span class="eyebrow">${c.eyebrow}</span><h2>${c.name}</h2><p>${c.summary}</p><h3>Strengths</h3>${chips(c.strengths)}</div></article>`).join('')}</section>`;}
function servicesPage(){return `${hero('Time-Tested Proficiency in HVAC Systems','From design-build planning to fabrication, installation, automation, service, retrofits, and environmental control, SURE Group supports the full mechanical lifecycle.', 'Services', button('Schedule Service','/contact/#service')+button('Request a Quote','/contact/#quote','secondary'))}<section class="section container services-layout"><aside class="side-nav"><h2>Services</h2>${services.map(s=>`<a href="#${slug(s[0])}">${s[0]}</a>`).join('')}</aside><div class="accordion-stack">${services.map((s,i)=>`<details id="${slug(s[0])}" class="accordion" ${i<3?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span>${s[0]}</summary><div><p>${s[1]}</p>${chips(s[2])}<a class="text-link" href="/contact/#quote">Discuss this service</a></div></details>`).join('')}</div></section>`;}
function industriesPage(){return `${hero('Mechanical Systems for Demanding Facilities','SURE Group supports commercial, institutional, industrial, laboratory, and utility environments where comfort, reliability, safety, and uptime matter.', 'Industries', button('View Projects','/projects/'))}<section class="section container industry-list">${industries.map(i=>`<article id="${slug(i[0])}" class="industry-detail"><div><span class="eyebrow">Industry</span><h2>${i[0]}</h2><p>${i[1]}</p></div><div><h3>Key facility concerns</h3>${chips(i[2])}<h3>Relevant services</h3>${chips(i[3])}<h3>Featured project examples</h3>${chips(i[4])}</div></article>`).join('')}</section>`;}
function projectsPage(){const industriesFilter=['All','Healthcare','Education','Government','Commercial','Industrial','Utility','Institutional']; const serviceFilter=['All','HVAC Construction','Chiller Plant','AHU/RTU','Hydronic Piping','Fabrication','Service','Environmental Control']; const companyFilter=['All','SURE Mechanical','Cincinnati Air','Thermolinear']; const group=(name,items,type)=>`<div><span>${name}</span><div class="filter-chips" role="group" aria-label="${name}">${items.map((x,i)=>`<button class="filter-chip ${i===0?'active':''}" data-filter-type="${type}" data-filter-value="${x}">${x}</button>`).join('')}</div></div>`; return `${hero('Where Expertise Meets Execution','Explore HVAC, mechanical construction, fabrication, service, and environmental control projects delivered by SURE Group companies.', 'Projects', button('Request Project Support','/contact/#quote'))}<section class="portfolio-section"><div class="container">${sectionHeading('Interactive portfolio','Project Experience Built for Critical Environments','Select any project to open an immersive, image-forward project view with scope details and gallery navigation.')}<div class="project-filter-bar project-filter-bar--dark">${group('By Industry',industriesFilter,'industry')}${group('By Service',serviceFilter,'service')}${group('By Company',companyFilter,'company')}</div><div class="project-grid" data-project-grid>${projects.map(projectPortfolioCard).join('')}</div></div></section>${expandedProjectModal()}<script type="application/json" id="project-data">${JSON.stringify(projects).replace(/</g, '\\u003c')}</script>`;}
function careersPage(){return `${hero('Build Your Career with SURE Group','Join a growing mechanical construction group that values safety, craft, technical skill, inclusive growth, and long-term opportunity.', 'Careers', button('Apply with SURE Mechanical','/contact/#careers')+button('Apply with Cincinnati Air','/contact/#careers','secondary'))}<section class="section container two-col"><div>${sectionHeading('Why work here','Build high-performance facilities with people who care about the craft')}<p>SURE Group teams work on commercial and institutional mechanical systems where skill, planning, safety, and accountability directly affect facility performance.</p><p>We support career growth through field mentorship, project leadership opportunities, and exposure to HVAC construction, fabrication, service, automation, and specialty environmental systems.</p></div><div class="quote-card"><h2>Apprenticeship and Workforce Development</h2><p>We are committed to developing apprentices, advancing experienced tradespeople, and expanding minority participation in technical construction fields.</p></div></section><section class="section section--light"><div class="container">${sectionHeading('Career paths','Opportunities across field, shop, office, and operations')}<div class="grid grid--5">${careers.map(c=>`<article class="mini-card"><h3>${c}</h3></article>`).join('')}</div></div></section><div class="container">${cta('Ready to apply?','Choose the application path that fits your background or contact us if you are not sure where to start.',button('SURE Mechanical Application','/contact/#careers')+button('Cincinnati Air Conditioning Company Application','/contact/#careers','secondary'))}</div>`;}
function contactForm(){const inquiries=['Request a Quote','Schedule Service','Preventative Maintenance','Design-Build Project','Fabrication','Environmental Control Systems','Careers','General Question']; const prefs=['SURE Group','SURE Mechanical','Cincinnati Air Conditioning Company','Thermolinear','Not Sure']; const input=(id,label,type='text')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" required><p class="error" id="${id}-error">Please enter ${label.toLowerCase()}.</p></div>`; return `<form class="contact-form" aria-describedby="form-note" novalidate><p id="form-note">Fields are labeled for accessibility. This static preview is ready to connect to your CRM or form handler.</p><div class="form-grid">${input('first-name','First Name')}${input('last-name','Last Name')}${input('company','Company')}${input('email','Email','email')}${input('phone','Phone','tel')}${input('project-location','Project Location')}<div class="field"><label for="inquiry-type">Inquiry Type</label><select id="inquiry-type" name="inquiry-type" required>${inquiries.map(x=>`<option>${x}</option>`).join('')}</select><p class="error">Please choose an inquiry type.</p></div><div class="field"><label for="preferred-company">Preferred Company</label><select id="preferred-company" name="preferred-company" required>${prefs.map(x=>`<option>${x}</option>`).join('')}</select><p class="error">Please choose a preferred company.</p></div><div class="field field--full"><label for="message">Message</label><textarea id="message" name="message" rows="6" required></textarea><p class="error">Please share a brief message.</p></div><div class="field field--full"><label for="file">Optional File Upload</label><input id="file" name="file" type="file"></div></div><button class="btn btn--primary" type="submit">Send Inquiry</button></form>`;}
function contactPage(){const cards=[['Request a Quote','Share drawings, scope, schedule, or facility needs.','quote'],['Schedule Service','Connect with commercial HVAC service support.','service'],['Custom Environmental Systems','Discuss clean rooms, dry rooms, chambers, and modular rooms.','environmental'],['Careers','Route applications and workforce questions.','careers']];return `${hero('Contact SURE Group','Request a quote, schedule service, discuss custom fabrication, or connect with the right company for your project.', 'Contact', button('Call '+site.phone,'tel:+15138981050')+button('Schedule Service','#service','secondary'))}<section class="section container"><div class="grid grid--4 routing-cards">${cards.map(c=>`<article id="${c[2]}" class="value-card"><h2>${c[0]}</h2><p>${c[1]}</p><a class="text-link" href="#contact-form">Start here</a></article>`).join('')}</div></section><section class="section section--light"><div class="container contact-layout"><div><span class="eyebrow">Headquarters</span><h2>SURE Group</h2><address>${site.address.join('<br>')}<br><a href="tel:+15138981050">${site.phone}</a><br>Fax: ${site.fax}</address><p>Use the form for commercial HVAC construction, service, fabrication, environmental control systems, preventative maintenance, and careers inquiries.</p></div><div id="contact-form">${contactForm()}</div></div></section>`;}

const pages = {'/': home(), '/about/': about(), '/companies/': companiesPage(), '/services/': servicesPage(), '/industries/': industriesPage(), '/projects/': projectsPage(), '/careers/': careersPage(), '/contact/': contactPage()};
async function writeSite(target) {
  await mkdir(join(target, 'assets'), { recursive: true });
  for (const [route, body] of Object.entries(pages)) {
    const file = route === '/' ? join(target, 'index.html') : join(target, route, 'index.html');
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, layout(route, body));
  }
  await copyFile(join(root, 'src/styles.css'), join(target, 'assets/styles.css'));
  await copyFile(join(root, 'src/main.js'), join(target, 'assets/main.js'));
}

await rm(out, { recursive: true, force: true });
await writeSite(out);
await writeSite(siteOut);
console.log(`Built ${Object.keys(pages).length} pages to dist/ and repository root`);
